### ISSUE TITLE
`adult` dataset encounters mu=nan sample in antecedent length=1

### ISSUE THREAD

**Issue by haojx07** [archon159/SELOR#2]
Hi Archon,

When running the sample code on adult dataset, the calculation for `mu` is nan for one sample (indexed 185 of the 239 length1 antecedents).
The observation is that the `satis_mask` for this sample is all `False`, the selected satis_ans is an empty list `[]` .

This is the breakpoint check for variable `mu` in the following stack
`__get_answer__`, dataset.py:885
`__init__`, dataset.py:792
`create_pretrain_dataset`, dataset.py:650
<module>, pretrain_consequent_estimator.py:130

![image](https://user-images.githubusercontent.com/10510523/205082079-17ae24e0-f0e4-4ef9-9f2d-1364e9758c87.png)

Reproducable on two different machines (one on Mac, one on Centos).

Previous commands
```
python3 base.py --dataset adult --base dnn --gpu 1
python3 extract_base_embedding.py --dataset adult --base dnn --gpu 1
python3 build_atom_pool.py --dataset adult --base dnn
python3 sample_antecedents.py --dataset adult --base dnn --gpu 1
python3 pretrain_consequent_estimator.py --dataset adult --base dnn --gpu 1
```
the nan of mu is in `pretrain_consequent_estimator.py`, the program will crash in `selor.py` as it encounters nan.
(no gpu is used, I set the value of `gpu` as `gpu = torch.device('cpu')`)

**Comment by archon159** [comment]
Thanks for your report.
I will check and solve it soon.

**Comment by archon159** [comment]
Hi, @haojx07 
I added a new commit to solve the issue.
Please check if it works with your environment.

**Comment by haojx07** [comment]
Hi @archon159 ,
It looks good so far, the NaNs disappear.

**Comment by archon159** [comment]
Great.
