### ISSUE TITLE
How to run the SELOR? is there any samples to run? Thanks!

### ISSUE THREAD

**Issue by joshua-xia** [archon159/SELOR#7]
Is there a samples to run and results to show?

**Comment by archon159** [comment]
Hi @joshua-xia , we are preparing a tutorial to run SELOR, but sorry to say it is currently not ready.
To run SELOR, please download the supported dataset (Yelp, Clickbait, or Adult) under "data" directory.
So your directory structure would be like following.

SELOR
>data
>>yelp_review_polarity_csv
>>>train.csv
>>>test.csv

>base.py
>selor.py
>...

After download, please "run_all.py".
The required argument would be dataset and base, which refers the dataset that you want use and base model (BERT, DNN) that you want to use.
I hope this comment can help you.

**Comment by joshua-xia** [comment]
> 
@archon159 Thanks, I am successfully running "run_all.py".
