### ISSUE TITLE
need the document about the config arguments settings

### ISSUE THREAD

**Issue by joshua-xia** [archon159/SELOR#9]
I am trying to training the SELOR using another data (Bert model) to do experiment of detecting the sentence is risk or not risk.
But some error happend when create_pretrain_dataset, for example:

Creating datasets for antecedent length 1 antecedents
torch.Size([1106, 1])
Creating datasets for antecedent length 2 antecedents
torch.Size([249, 2])
n_sample = 249

Traceback (most recent call last):
  File "/home/joshua/SELOR/pretrain_consequent_estimator.py", line 121, in <module>
    pretrain_dataset = ds.create_pretrain_dataset(
  File "/home/joshua/SELOR/selor_utils/dataset.py", line 956, in create_pretrain_dataset
    p_ds = PretrainDataset(
  File "/home/joshua/SELOR/selor_utils/dataset.py", line 299, in __init__
    assert n_sample % num_classes == 0
AssertionError

Another problem is:

PretrainDataset 's __init__ never end because the following line dead loop:
    while not all(sample_dict[i].done for i in range(num_classes)):

I think maybe these problems are related to the config arguments setting, so would you please provide the document about the config arguments settings and explain how to set the config accroding to the train/test data.

Thanks!

**Comment by archon159** [comment]
Hi, you can find the explanation about config arguments in the help messages from selor_utils/utils.py.
And it seems that your dataset is highly imbalanced.
If the init of PretrainDataset fell into the dead loop of "while not all(sample_dict[i].done for i in range(num_classes))",
it means that your chosen antecedents all belongs to one class, risky or non-risky.

I suggest you several way that may works.

1) Make min_df=0 and max_df=1.0
It would help that the seldom cases would not be filtered out.

2) Check you atoms.
Make the class ratio of atoms to be uniform if it is possible.

3) Manual Sampling.
If the class ratio of atoms is highly imbalanced, It is possible that the random sampling code choose the antecedents only from the dominating class. In this case, manually giving some constraint in the sampling would help.

**Comment by joshua-xia** [comment]
> * Check you atoms.
>   Make the class ratio of atoms to be uniform if it is possible.
> * Manual Sampling.
>   If the class ratio of atoms is high

Yes, the dataset is highly imbalanced,

Thanks a lot! I will try your suggestion.

**Comment by joshua-xia** [comment]
Thanks @archon159  very much, the code run successfully on my dataset.

I have another question: the antecedents are AND between the atoms, I wonder how to implement the OR (only OR is enough for me) between atoms, Thanks!

**Comment by archon159** [comment]
Hi @joshua-xia,

The easiest way to implement "OR" is using multiple heads.
If you see selor.py line129, you can control the number of heads.
Thanks.

**Comment by joshua-xia** [comment]
> line129

Thanks, it is real easy implementation, I am testing your suggestion;

I just confirm you understood my means:

I want antecedent to be OR between atoms:

line 629 in selor_utils)/train_eval.py:
            antecedent_str = ' & '.join([atom.display_str for atom in antecedent])

should be 
             antecedent_str = ' | '.join([atom.display_str for atom in antecedent])

just change heads = 2 or 3 or 4 works?

**Comment by archon159** [comment]
So, each heads gives you rule individually.
As they are independent, we regards them as OR.
For example, if you want 4-length OR rules, please use antecedent_len=1, heads=4.

**Comment by joshua-xia** [comment]
> So, each heads gives you rule individually.
> As they are independent, we regards them as OR.
> For example, if you want 4-length OR rules, please use antecedent_len=1, heads=4.

got, both antecedent_len and heads need to be modified.

**Comment by joshua-xia** [comment]
selor.py line 121:
# Freeze the consequent estimator
    for p in ce_model.parameters():
        p.requires_grad=False

Why we need freeze the consequent estimator? it seems performance of selor is better if we don't freeze.

**Comment by archon159** [comment]
It depends on dataset.
If it is better, it may not be the problem.

**Comment by joshua-xia** [comment]
another question, use the yelp dataset and bert model as example:
 
The atoms and antecedents are generated from the train dataset, so if a test case (test instance) contain the Positive or Negative words which not exist in train dataset, then the Positive or Negative words can NOT be in the explanation results, right?

It seems the defect of SELOR?

**Comment by archon159** [comment]
Right. Our basic assumption is, the training dataset and test dataset has come from the same distribution.

**Comment by joshua-xia** [comment]
@archon159  where can I download clickbait and adult dataset? can you provide the url links? Thanks!
